# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AvocadoCrypto.ui'
#
# Created: Tue Mar  1 19:03:22 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.setWindowModality(QtCore.Qt.NonModal)
        dialog.setEnabled(True)
        dialog.resize(588, 329)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialog.setWindowIcon(icon)
        dialog.setStatusTip("")
        dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.button_decrypt = QtGui.QPushButton(dialog)
        self.button_decrypt.setEnabled(False)
        self.button_decrypt.setGeometry(QtCore.QRect(470, 290, 101, 27))
        self.button_decrypt.setObjectName("button_decrypt")
        self.button_encrypt = QtGui.QPushButton(dialog)
        self.button_encrypt.setEnabled(False)
        self.button_encrypt.setGeometry(QtCore.QRect(350, 290, 101, 27))
        self.button_encrypt.setObjectName("button_encrypt")
        self.group_box_source = QtGui.QGroupBox(dialog)
        self.group_box_source.setGeometry(QtCore.QRect(350, 10, 181, 61))
        self.group_box_source.setObjectName("group_box_source")
        self.radio_button_text_source = QtGui.QRadioButton(self.group_box_source)
        self.radio_button_text_source.setGeometry(QtCore.QRect(10, 30, 61, 22))
        self.radio_button_text_source.setChecked(False)
        self.radio_button_text_source.setObjectName("radio_button_text_source")
        self.radio_button_file_source = QtGui.QRadioButton(self.group_box_source)
        self.radio_button_file_source.setGeometry(QtCore.QRect(101, 30, 81, 22))
        self.radio_button_file_source.setChecked(True)
        self.radio_button_file_source.setObjectName("radio_button_file_source")
        self.group_box_keys = QtGui.QGroupBox(dialog)
        self.group_box_keys.setGeometry(QtCore.QRect(10, 10, 331, 321))
        self.group_box_keys.setObjectName("group_box_keys")
        self.tab_widget_keys = QtGui.QTabWidget(self.group_box_keys)
        self.tab_widget_keys.setGeometry(QtCore.QRect(0, 30, 321, 281))
        self.tab_widget_keys.setObjectName("tab_widget_keys")
        self.tab_rsa = QtGui.QWidget()
        self.tab_rsa.setObjectName("tab_rsa")
        self.group_box_own_rsa = QtGui.QGroupBox(self.tab_rsa)
        self.group_box_own_rsa.setGeometry(QtCore.QRect(0, 0, 221, 91))
        self.group_box_own_rsa.setObjectName("group_box_own_rsa")
        self.line_own_private = QtGui.QLineEdit(self.group_box_own_rsa)
        self.line_own_private.setEnabled(False)
        self.line_own_private.setGeometry(QtCore.QRect(82, 20, 131, 27))
        self.line_own_private.setObjectName("line_own_private")
        self.line_own_public = QtGui.QLineEdit(self.group_box_own_rsa)
        self.line_own_public.setEnabled(False)
        self.line_own_public.setGeometry(QtCore.QRect(80, 60, 131, 27))
        self.line_own_public.setObjectName("line_own_public")
        self.label_own_private = QtGui.QLabel(self.group_box_own_rsa)
        self.label_own_private.setGeometry(QtCore.QRect(20, 30, 56, 17))
        self.label_own_private.setObjectName("label_own_private")
        self.label_own_public = QtGui.QLabel(self.group_box_own_rsa)
        self.label_own_public.setGeometry(QtCore.QRect(20, 70, 56, 17))
        self.label_own_public.setObjectName("label_own_public")
        self.group_box_rec_rsa = QtGui.QGroupBox(self.tab_rsa)
        self.group_box_rec_rsa.setGeometry(QtCore.QRect(0, 100, 221, 101))
        self.group_box_rec_rsa.setObjectName("group_box_rec_rsa")
        self.line_rec_private = QtGui.QLineEdit(self.group_box_rec_rsa)
        self.line_rec_private.setEnabled(False)
        self.line_rec_private.setGeometry(QtCore.QRect(80, 20, 131, 27))
        self.line_rec_private.setObjectName("line_rec_private")
        self.label_rec_private = QtGui.QLabel(self.group_box_rec_rsa)
        self.label_rec_private.setGeometry(QtCore.QRect(20, 30, 56, 17))
        self.label_rec_private.setObjectName("label_rec_private")
        self.label_rec_public = QtGui.QLabel(self.group_box_rec_rsa)
        self.label_rec_public.setGeometry(QtCore.QRect(20, 70, 56, 17))
        self.label_rec_public.setObjectName("label_rec_public")
        self.line_rec_public = QtGui.QLineEdit(self.group_box_rec_rsa)
        self.line_rec_public.setEnabled(False)
        self.line_rec_public.setGeometry(QtCore.QRect(80, 60, 131, 27))
        self.line_rec_public.setObjectName("line_rec_public")
        self.button_select_own_private = QtGui.QPushButton(self.tab_rsa)
        self.button_select_own_private.setGeometry(QtCore.QRect(220, 20, 85, 27))
        self.button_select_own_private.setObjectName("button_select_own_private")
        self.button_select_own_public = QtGui.QPushButton(self.tab_rsa)
        self.button_select_own_public.setGeometry(QtCore.QRect(220, 60, 85, 27))
        self.button_select_own_public.setObjectName("button_select_own_public")
        self.button_select_rec_private = QtGui.QPushButton(self.tab_rsa)
        self.button_select_rec_private.setGeometry(QtCore.QRect(220, 120, 85, 27))
        self.button_select_rec_private.setObjectName("button_select_rec_private")
        self.button_select_rec_public = QtGui.QPushButton(self.tab_rsa)
        self.button_select_rec_public.setGeometry(QtCore.QRect(220, 160, 85, 27))
        self.button_select_rec_public.setObjectName("button_select_rec_public")
        self.tab_widget_keys.addTab(self.tab_rsa, "")
        self.tab_aes = QtGui.QWidget()
        self.tab_aes.setObjectName("tab_aes")
        self.button_load_aes = QtGui.QPushButton(self.tab_aes)
        self.button_load_aes.setEnabled(False)
        self.button_load_aes.setGeometry(QtCore.QRect(10, 10, 161, 26))
        self.button_load_aes.setObjectName("button_load_aes")
        self.button_save_aes = QtGui.QPushButton(self.tab_aes)
        self.button_save_aes.setEnabled(False)
        self.button_save_aes.setGeometry(QtCore.QRect(10, 50, 161, 26))
        self.button_save_aes.setObjectName("button_save_aes")
        self.tab_widget_keys.addTab(self.tab_aes, "")
        self.tab_tools = QtGui.QWidget()
        self.tab_tools.setObjectName("tab_tools")
        self.button_gen_keys = QtGui.QPushButton(self.tab_tools)
        self.button_gen_keys.setGeometry(QtCore.QRect(10, 10, 191, 27))
        self.button_gen_keys.setObjectName("button_gen_keys")
        self.button_gen_aes = QtGui.QPushButton(self.tab_tools)
        self.button_gen_aes.setGeometry(QtCore.QRect(10, 50, 191, 27))
        self.button_gen_aes.setObjectName("button_gen_aes")
        self.button_gen_own_rsa = QtGui.QPushButton(self.tab_tools)
        self.button_gen_own_rsa.setGeometry(QtCore.QRect(10, 100, 191, 27))
        self.button_gen_own_rsa.setObjectName("button_gen_own_rsa")
        self.button_gen_rec_rsa = QtGui.QPushButton(self.tab_tools)
        self.button_gen_rec_rsa.setGeometry(QtCore.QRect(10, 130, 191, 27))
        self.button_gen_rec_rsa.setObjectName("button_gen_rec_rsa")
        self.button_switch_rsa = QtGui.QPushButton(self.tab_tools)
        self.button_switch_rsa.setEnabled(False)
        self.button_switch_rsa.setGeometry(QtCore.QRect(10, 170, 191, 27))
        self.button_switch_rsa.setObjectName("button_switch_rsa")
        self.tab_widget_keys.addTab(self.tab_tools, "")
        self.tab_stegano = QtGui.QWidget()
        self.tab_stegano.setObjectName("tab_stegano")
        self.check_box_stegano = QtGui.QCheckBox(self.tab_stegano)
        self.check_box_stegano.setEnabled(True)
        self.check_box_stegano.setGeometry(QtCore.QRect(10, 10, 71, 22))
        self.check_box_stegano.setObjectName("check_box_stegano")
        self.button_image_select = QtGui.QPushButton(self.tab_stegano)
        self.button_image_select.setEnabled(False)
        self.button_image_select.setGeometry(QtCore.QRect(220, 10, 81, 27))
        self.button_image_select.setObjectName("button_image_select")
        self.stegano_preview = QtGui.QGraphicsView(self.tab_stegano)
        self.stegano_preview.setGeometry(QtCore.QRect(10, 40, 291, 201))
        self.stegano_preview.setObjectName("stegano_preview")
        self.tab_widget_keys.addTab(self.tab_stegano, "")
        self.plain_text_edit = QtGui.QPlainTextEdit(dialog)
        self.plain_text_edit.setEnabled(False)
        self.plain_text_edit.setGeometry(QtCore.QRect(350, 140, 221, 111))
        self.plain_text_edit.setObjectName("plain_text_edit")
        self.button_file_select = QtGui.QPushButton(dialog)
        self.button_file_select.setGeometry(QtCore.QRect(350, 70, 81, 27))
        self.button_file_select.setObjectName("button_file_select")
        self.label_selected_file = QtGui.QLabel(dialog)
        self.label_selected_file.setGeometry(QtCore.QRect(360, 110, 91, 17))
        self.label_selected_file.setObjectName("label_selected_file")
        self.check_box_md5 = QtGui.QCheckBox(dialog)
        self.check_box_md5.setEnabled(True)
        self.check_box_md5.setGeometry(QtCore.QRect(350, 260, 51, 22))
        self.check_box_md5.setObjectName("check_box_md5")

        self.retranslateUi(dialog)
        self.tab_widget_keys.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(QtGui.QApplication.translate("dialog", "AvocadoCrypto", None, QtGui.QApplication.UnicodeUTF8))
        self.button_decrypt.setText(QtGui.QApplication.translate("dialog", "Decrypt", None, QtGui.QApplication.UnicodeUTF8))
        self.button_encrypt.setText(QtGui.QApplication.translate("dialog", "Encrypt", None, QtGui.QApplication.UnicodeUTF8))
        self.group_box_source.setTitle(QtGui.QApplication.translate("dialog", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_button_text_source.setText(QtGui.QApplication.translate("dialog", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_button_file_source.setText(QtGui.QApplication.translate("dialog", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.group_box_keys.setTitle(QtGui.QApplication.translate("dialog", "Keys", None, QtGui.QApplication.UnicodeUTF8))
        self.group_box_own_rsa.setTitle(QtGui.QApplication.translate("dialog", "Own RSA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_own_private.setText(QtGui.QApplication.translate("dialog", "Private:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_own_public.setText(QtGui.QApplication.translate("dialog", "Public:", None, QtGui.QApplication.UnicodeUTF8))
        self.group_box_rec_rsa.setTitle(QtGui.QApplication.translate("dialog", "Sender / Receiver RSA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_private.setText(QtGui.QApplication.translate("dialog", "Private:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_public.setText(QtGui.QApplication.translate("dialog", "Public:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_select_own_private.setText(QtGui.QApplication.translate("dialog", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.button_select_own_public.setText(QtGui.QApplication.translate("dialog", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.button_select_rec_private.setText(QtGui.QApplication.translate("dialog", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.button_select_rec_public.setText(QtGui.QApplication.translate("dialog", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget_keys.setTabText(self.tab_widget_keys.indexOf(self.tab_rsa), QtGui.QApplication.translate("dialog", "RSA", None, QtGui.QApplication.UnicodeUTF8))
        self.button_load_aes.setText(QtGui.QApplication.translate("dialog", "Load Encrypted AES", None, QtGui.QApplication.UnicodeUTF8))
        self.button_save_aes.setText(QtGui.QApplication.translate("dialog", "Encrypt and save AES", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget_keys.setTabText(self.tab_widget_keys.indexOf(self.tab_aes), QtGui.QApplication.translate("dialog", "AES", None, QtGui.QApplication.UnicodeUTF8))
        self.button_gen_keys.setText(QtGui.QApplication.translate("dialog", "Generate all keys", None, QtGui.QApplication.UnicodeUTF8))
        self.button_gen_aes.setText(QtGui.QApplication.translate("dialog", "Generate AES", None, QtGui.QApplication.UnicodeUTF8))
        self.button_gen_own_rsa.setText(QtGui.QApplication.translate("dialog", "Generate own RSA", None, QtGui.QApplication.UnicodeUTF8))
        self.button_gen_rec_rsa.setText(QtGui.QApplication.translate("dialog", "Generate Sender/Receiver RSA", None, QtGui.QApplication.UnicodeUTF8))
        self.button_switch_rsa.setText(QtGui.QApplication.translate("dialog", "Switch own <> Sender/Receiver", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget_keys.setTabText(self.tab_widget_keys.indexOf(self.tab_tools), QtGui.QApplication.translate("dialog", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_stegano.setText(QtGui.QApplication.translate("dialog", "Actief", None, QtGui.QApplication.UnicodeUTF8))
        self.button_image_select.setText(QtGui.QApplication.translate("dialog", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget_keys.setTabText(self.tab_widget_keys.indexOf(self.tab_stegano), QtGui.QApplication.translate("dialog", "Steganografie", None, QtGui.QApplication.UnicodeUTF8))
        self.button_file_select.setText(QtGui.QApplication.translate("dialog", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_selected_file.setText(QtGui.QApplication.translate("dialog", "(no file selected)", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_md5.setText(QtGui.QApplication.translate("dialog", "MD5", None, QtGui.QApplication.UnicodeUTF8))

