# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/AvocadoCrypto.ui'
#
# Created: Thu Dec 17 21:03:13 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.setWindowModality(QtCore.Qt.NonModal)
        dialog.setEnabled(True)
        dialog.resize(511, 301)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialog.setWindowIcon(icon)
        dialog.setStatusTip("")
        dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.button_decrypt = QtGui.QPushButton(dialog)
        self.button_decrypt.setEnabled(False)
        self.button_decrypt.setGeometry(QtCore.QRect(410, 260, 81, 27))
        self.button_decrypt.setObjectName("button_decrypt")
        self.button_encrypt = QtGui.QPushButton(dialog)
        self.button_encrypt.setEnabled(False)
        self.button_encrypt.setGeometry(QtCore.QRect(330, 260, 81, 27))
        self.button_encrypt.setObjectName("button_encrypt")
        self.group_box_source = QtGui.QGroupBox(dialog)
        self.group_box_source.setGeometry(QtCore.QRect(270, 10, 181, 61))
        self.group_box_source.setObjectName("group_box_source")
        self.radio_button_text_source = QtGui.QRadioButton(self.group_box_source)
        self.radio_button_text_source.setGeometry(QtCore.QRect(10, 30, 61, 22))
        self.radio_button_text_source.setChecked(False)
        self.radio_button_text_source.setObjectName("radio_button_text_source")
        self.radio_button_file_source = QtGui.QRadioButton(self.group_box_source)
        self.radio_button_file_source.setGeometry(QtCore.QRect(101, 30, 81, 22))
        self.radio_button_file_source.setChecked(True)
        self.radio_button_file_source.setObjectName("radio_button_file_source")
        self.group_box_keys = QtGui.QGroupBox(dialog)
        self.group_box_keys.setGeometry(QtCore.QRect(10, 10, 231, 321))
        self.group_box_keys.setObjectName("group_box_keys")
        self.tab_widget_keys = QtGui.QTabWidget(self.group_box_keys)
        self.tab_widget_keys.setGeometry(QtCore.QRect(0, 30, 231, 251))
        self.tab_widget_keys.setObjectName("tab_widget_keys")
        self.tab_tools = QtGui.QWidget()
        self.tab_tools.setObjectName("tab_tools")
        self.button_gen_keys = QtGui.QPushButton(self.tab_tools)
        self.button_gen_keys.setGeometry(QtCore.QRect(10, 10, 191, 27))
        self.button_gen_keys.setObjectName("button_gen_keys")
        self.button_gen_aes = QtGui.QPushButton(self.tab_tools)
        self.button_gen_aes.setGeometry(QtCore.QRect(10, 50, 191, 27))
        self.button_gen_aes.setObjectName("button_gen_aes")
        self.button_gen_own_rsa = QtGui.QPushButton(self.tab_tools)
        self.button_gen_own_rsa.setGeometry(QtCore.QRect(10, 100, 191, 27))
        self.button_gen_own_rsa.setObjectName("button_gen_own_rsa")
        self.button_gen_rec_rsa = QtGui.QPushButton(self.tab_tools)
        self.button_gen_rec_rsa.setGeometry(QtCore.QRect(10, 130, 191, 27))
        self.button_gen_rec_rsa.setObjectName("button_gen_rec_rsa")
        self.button_switch_rsa = QtGui.QPushButton(self.tab_tools)
        self.button_switch_rsa.setEnabled(False)
        self.button_switch_rsa.setGeometry(QtCore.QRect(10, 170, 191, 27))
        self.button_switch_rsa.setObjectName("button_switch_rsa")
        self.tab_widget_keys.addTab(self.tab_tools, "")
        self.tab_rsa = QtGui.QWidget()
        self.tab_rsa.setObjectName("tab_rsa")
        self.group_box_own_rsa = QtGui.QGroupBox(self.tab_rsa)
        self.group_box_own_rsa.setGeometry(QtCore.QRect(0, 0, 221, 91))
        self.group_box_own_rsa.setObjectName("group_box_own_rsa")
        self.line_own_private = QtGui.QLineEdit(self.group_box_own_rsa)
        self.line_own_private.setEnabled(False)
        self.line_own_private.setGeometry(QtCore.QRect(82, 20, 131, 27))
        self.line_own_private.setObjectName("line_own_private")
        self.line_own_public = QtGui.QLineEdit(self.group_box_own_rsa)
        self.line_own_public.setEnabled(False)
        self.line_own_public.setGeometry(QtCore.QRect(80, 60, 131, 27))
        self.line_own_public.setObjectName("line_own_public")
        self.label_own_private = QtGui.QLabel(self.group_box_own_rsa)
        self.label_own_private.setGeometry(QtCore.QRect(20, 30, 56, 17))
        self.label_own_private.setObjectName("label_own_private")
        self.label_own_public = QtGui.QLabel(self.group_box_own_rsa)
        self.label_own_public.setGeometry(QtCore.QRect(20, 70, 56, 17))
        self.label_own_public.setObjectName("label_own_public")
        self.group_box_rec_rsa = QtGui.QGroupBox(self.tab_rsa)
        self.group_box_rec_rsa.setGeometry(QtCore.QRect(0, 100, 221, 101))
        self.group_box_rec_rsa.setObjectName("group_box_rec_rsa")
        self.line_rec_private = QtGui.QLineEdit(self.group_box_rec_rsa)
        self.line_rec_private.setEnabled(False)
        self.line_rec_private.setGeometry(QtCore.QRect(80, 20, 131, 27))
        self.line_rec_private.setObjectName("line_rec_private")
        self.label_rec_private = QtGui.QLabel(self.group_box_rec_rsa)
        self.label_rec_private.setGeometry(QtCore.QRect(20, 30, 56, 17))
        self.label_rec_private.setObjectName("label_rec_private")
        self.label_rec_public = QtGui.QLabel(self.group_box_rec_rsa)
        self.label_rec_public.setGeometry(QtCore.QRect(20, 70, 56, 17))
        self.label_rec_public.setObjectName("label_rec_public")
        self.line_rec_public = QtGui.QLineEdit(self.group_box_rec_rsa)
        self.line_rec_public.setEnabled(False)
        self.line_rec_public.setGeometry(QtCore.QRect(80, 60, 131, 27))
        self.line_rec_public.setObjectName("line_rec_public")
        self.tab_widget_keys.addTab(self.tab_rsa, "")
        self.plain_text_edit = QtGui.QPlainTextEdit(dialog)
        self.plain_text_edit.setEnabled(False)
        self.plain_text_edit.setGeometry(QtCore.QRect(270, 140, 221, 111))
        self.plain_text_edit.setObjectName("plain_text_edit")
        self.button_file_select = QtGui.QPushButton(dialog)
        self.button_file_select.setGeometry(QtCore.QRect(270, 70, 81, 27))
        self.button_file_select.setObjectName("button_file_select")
        self.label_selected_file = QtGui.QLabel(dialog)
        self.label_selected_file.setGeometry(QtCore.QRect(280, 110, 91, 17))
        self.label_selected_file.setObjectName("label_selected_file")
        self.check_box_md5 = QtGui.QCheckBox(dialog)
        self.check_box_md5.setGeometry(QtCore.QRect(270, 260, 51, 22))
        self.check_box_md5.setObjectName("check_box_md5")

        self.retranslateUi(dialog)
        self.tab_widget_keys.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(QtGui.QApplication.translate("dialog", "AvocadoCrypto", None, QtGui.QApplication.UnicodeUTF8))
        self.button_decrypt.setText(QtGui.QApplication.translate("dialog", "Decrypt", None, QtGui.QApplication.UnicodeUTF8))
        self.button_encrypt.setText(QtGui.QApplication.translate("dialog", "Encrypt", None, QtGui.QApplication.UnicodeUTF8))
        self.group_box_source.setTitle(QtGui.QApplication.translate("dialog", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_button_text_source.setText(QtGui.QApplication.translate("dialog", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_button_file_source.setText(QtGui.QApplication.translate("dialog", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.group_box_keys.setTitle(QtGui.QApplication.translate("dialog", "Keys", None, QtGui.QApplication.UnicodeUTF8))
        self.button_gen_keys.setText(QtGui.QApplication.translate("dialog", "Generate all keys", None, QtGui.QApplication.UnicodeUTF8))
        self.button_gen_aes.setText(QtGui.QApplication.translate("dialog", "Generate AES", None, QtGui.QApplication.UnicodeUTF8))
        self.button_gen_own_rsa.setText(QtGui.QApplication.translate("dialog", "Generate own RSA", None, QtGui.QApplication.UnicodeUTF8))
        self.button_gen_rec_rsa.setText(QtGui.QApplication.translate("dialog", "Generate Sender/Receiver RSA", None, QtGui.QApplication.UnicodeUTF8))
        self.button_switch_rsa.setText(QtGui.QApplication.translate("dialog", "Switch own <> Sender/Receiver", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget_keys.setTabText(self.tab_widget_keys.indexOf(self.tab_tools), QtGui.QApplication.translate("dialog", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.group_box_own_rsa.setTitle(QtGui.QApplication.translate("dialog", "Own RSA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_own_private.setText(QtGui.QApplication.translate("dialog", "Private:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_own_public.setText(QtGui.QApplication.translate("dialog", "Public:", None, QtGui.QApplication.UnicodeUTF8))
        self.group_box_rec_rsa.setTitle(QtGui.QApplication.translate("dialog", "Sender / Receiver RSA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_private.setText(QtGui.QApplication.translate("dialog", "Private:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec_public.setText(QtGui.QApplication.translate("dialog", "Public:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget_keys.setTabText(self.tab_widget_keys.indexOf(self.tab_rsa), QtGui.QApplication.translate("dialog", "RSA", None, QtGui.QApplication.UnicodeUTF8))
        self.button_file_select.setText(QtGui.QApplication.translate("dialog", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_selected_file.setText(QtGui.QApplication.translate("dialog", "(no file selected)", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_md5.setText(QtGui.QApplication.translate("dialog", "MD5", None, QtGui.QApplication.UnicodeUTF8))

